### ISSUE TITLE
Classical Theme types (and functions)

### ISSUE THREAD

**Issue by bcmoseley** [openmusictheory/openmusictheory.github.io#10]
This page is in good shape. We could make the graphics look nicer by giving them transparent background and updating the fonts to match whatever style we settle on. @kshaffer Should we set a standard font for graphic files in the textbook? 

And for some reason the [classical theme functions](http://openmusictheory.com/themeFunctions.html) isn't linked to on the table of contents. It should be grouped wit this.

Could be useful to create a nice printable PDF of these theme types as well.

**Comment by kshaffer** [comment]
That all sounds good. We should discuss theming, in general, and accessibility, too. So it's best to make font decisions then. I agree about the graphics.
