### ISSUE TITLE
Pick new color for links

### ISSUE THREAD

**Issue by kshaffer** [openmusictheory/openmusictheory.github.io#40]
for greater readability, accessibility.

**Comment by mmcclimon** [comment]
Bumping this...I can barely read the links if I'm using the classroom projector. I'd suggest `#3F81A2` for links and `#285267` for visited (both related to the current link color, so the look should be intact: http://colllor.com/8AB9D1). 

Also (I know @bcmoseley doesn't like them), for accessibility, [links should probably be underlined](http://webaim.org/techniques/hypertext/link_text#appearance) .

**Comment by bcmoseley** [comment]
Just changed this. Also added dotted underlines on hover. Does that help @mmcclimon? What do you think @kshaffer?

**Comment by mmcclimon** [comment]
_So_ much better!! :+1: :+1: :+1:
