### ISSUE TITLE
Images are broken on some pages

### ISSUE THREAD

**Issue by aycyang** [openmusictheory/openmusictheory.github.io#49]
Here is an example of the problematic &lt;img&gt; tag, taken from at http://openmusictheory.com/triads.html

```
<img src="/http://openmusictheory.com/Graphics/triadsSeventhChords/circleOfThirds-seventhRTFS.svg" alt="A seventh chord (A, C, E, G) on the diatonic circle of thirds.">
```

Note the src property has a leading slash which leads the browser to append the following characters to the current URL path.

---

The result is broken images, like this:

![screenshot of broken image](http://puu.sh/vYlmi/27083744df.png)

I see the same problem in the following pages.

* http://openmusictheory.com/protonotation.html
* http://openmusictheory.com/pitches.html
* http://openmusictheory.com/scales.html
* I've barely looked through any of the pages, so there may be more.

I noticed there is no such issue when viewing from the Github repo itself. Also, some pages don't have this problem. As far as I can tell, the difference is that the problematic pages use the Markdown image syntax, whereas the non-problematic pages directly use HTML img tags.

**Comment by zsszatmari** [comment]
I can attest that images are broken on most pages.

**Comment by kshaffer** [comment]
Thanks, it looks like GitHub pages changed something about the way they handle that style of link which has broken it. Needs to be changed system-wide for those older pages that incorporate it. I'll take a look at it in the next few days, unless someone beats me to it with a pull request!

**Comment by zsszatmari** [comment]
Awesome, thanks!

**Comment by kshaffer** [comment]
The specific problem is that links like 

    ![A triad (A, C, E) on the diatonic circle of thirds.][circleOfThirds-triad]

with

    [circleOfThirds-triad]: Graphics/triadsSeventhChords/circleOfThirds-triad.svg

at the end of the file no longer seems to work. Needs to be replaced with

    ![A triad (A, C, E) on the diatonic circle of thirds.][Graphics/triadsSeventhChords/circleOfThirds-triad.svg]

or better (to include a link to the full-size file):

    [![A triad (A, C, E) on the diatonic circle of thirds.][Graphics/triadsSeventhChords/circleOfThirds-triad.svg]](Graphics/triadsSeventhChords/circleOfThirds-triad.svg)

(or the raw HTML equivalent).

**Comment by zsszatmari** [comment]
I am not very familiar with Ruby, but one idea that might be worth investigating is to specify an exact, older Jekyll version in the Gemfile? Maybe that would solve the problem.

**Comment by kshaffer** [comment]
Should be fixed now! I did a site-wide find-and-replace so now all media links point to `{{ site.url }}/Graphics...` rather than just the local path. That seems to have fixed the issue. Please let me know if you find any other errors I haven't seen, and I'll take care of them.

Thanks for letting me know! I'm not teaching music theory right now, so I'm not looking at the site on a daily basis like I used to. :)

**Comment by zsszatmari** [comment]
Seems good so far, Thank You!

**Comment by aycyang** [comment]
Thanks! I am loving openmusictheory and I'm happy to see this fixed 😄
